### ISSUE TITLE
Model Checkpoint Request

### ISSUE THREAD

**Issue by h0ngxuanli** [fudan-generative-vision/dynamicPDB#10]
Thanks authors for such an inspiring and interesting work.

I am wondering whether you could provide the checkpoints for the trained model?

**Comment by cnexah** [comment]
Thank you for your interest.
We provide the checkpoint in https://huggingface.co/fudan-generative-ai/dynamicPDB/tree/main, which is trained using around 210 proteins.

**Comment by h0ngxuanli** [comment]
Thanks!!!! Really appreciate it!!!

**Comment by 193384770** [comment]
Can I ask if this checkpoint can be applied in 4D diffusion?
